project:
  output-dir: docs
  type: book
  
lang: zh

book:
  title: "OpenCL 笔记"
  author: "shiyu-hong"
  date: today
  date-format: long
  chapters:
    - index.qmd
    - intro.qmd
    
    - part: "如何配置 OpenCL 环境"
      chapters: 
        - "content/chap01_environment/vcpkg.qmd"

format:
  html:
    theme:
      dark: superhero
      light: cosmo
  pdf:
    documentclass: book
    include-in-header: "tex/preamble.tex"
    geometry:
      - tmargin=2.5cm
      - bmargin=2.5cm
      - lmargin=3.0cm
      - rmargin=2.0cm

editor: visual

